#apiVersion: v1
#kind: Service
#metadata:
#  name: mysql-cip
#  namespace: mysql
#spec:
#  type: ClusterIP
#  selector:
#    app: mysql
#  ports:
#  - protocol: TCP
#    port: 3306
#    targetPort: 3306
#
#
#---

apiVersion: v1
kind: Service
metadata:
  name: todoapp-cip
  namespace: todoapp
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080