apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  namespace: todoapp
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: trinida/todoapp:2.1.1
        imagePullPolicy: Always
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: app-secrets-volume
          mountPath: /src/secrets
          readOnly: true
        - name: app-config-volume
          mountPath: /src/configs
          readOnly: true
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 800m
        env:
        - name: DB_MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_MYSQL_DATABASE
        - name: DB_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_MYSQL_PASSWORD
        - name: DB_MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_MYSQL_USER
        - name: DB_HOST_NAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_HOST_NAME
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PYTHONUNBUFFERED
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SECRET_KEY
#        - name: CONNECTION_STRING
#          valueFrom:
#            secretKeyRef:
#              name: app-secret
#              key: CONNECTION_STRING
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: api/health
            port: 8080
          initialDelaySeconds: 100
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-data
      - name: app-secrets-volume
        secret:
          secretName: app-secret
      - name: app-config-volume
        configMap:
          name: app-config